### ISSUE TITLE
(feature) Add GitHub App retriever for Relay Proxy

### ISSUE THREAD

**Issue by Gregory-Berkman-Imprivata** [thomaspoignant/go-feature-flag#1334]
### Requirements

The current Github retriever requires a GitHub user Personal Access Token. For some organizations, this can require a new user be created and can cause additional expense. Also a user has a rate limit of 5000 requests per hour while a GitHub App has far larger capacity. The explicit purpose of GitHub Apps are to enable integration without requiring additional users so a new GitHub Apps retriever rather than a GitHub PAT retriever would be a better mechanism for polling GitHub for feature flag configurations.

**Comment by thomaspoignant** [comment]
Hi @Gregory-Berkman-Imprivata, I am not super familiar with Github Apps.
Can you tell me how you see this working with GO Feature Flag? 

If I understand correctly in the doc https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps#building-a-github-app building a GitHub requires hosting a service.

How to envisage that?
Who will be in charge of that?

**Comment by lorelei-rupp-imprivata** [comment]
@thomaspoignant sorry that we never got back to you here. So instead of creating a github PAT token to use with this for connecting to github, you would create in your github enterprise a github app, its a similar process to creating a PAT, and you end up with a token at the end of the day. This token could then be used by feature flags to connect back to github. The token has better rate limiting support at the github level

Currently we are seeing the feature flag proxy crash/restart and throw connection refused errors. We currently have it using the same gihub PAT token in all our envs, and we suspect its being rate limited by github but are not 100%. This feature would help us and others I think to support github apps and PATs

**Comment by thomaspoignant** [comment]
@lorelei-rupp-imprivata thanks for the inputs.
If it is just a different token to access the Github API from my understanding you can already use it to call the API.

Have you tried it?
Do you have any log of those crashes to be able to understand them?

**Comment by lorelei-rupp-imprivata** [comment]
> @lorelei-rupp-imprivata thanks for the inputs. If it is just a different token to access the Github API from my understanding you can already use it to call the API.
> 
> Have you tried it? Do you have any log of those crashes to be able to understand them?

We will see if we can try passing that token, we have not tried, it. Currently we just have the same PAT used for each of our envs. I believe the logs do not have much in them when it crashes. I will ask the team to provide more details

**Comment by thomaspoignant** [comment]
@lorelei-rupp-imprivata please let me know how it goes, I would love to understand how it works.

**Comment by Volodymyr-Maiboroda-Imprivata** [comment]
@thomaspoignant FYI, the relay proxy pod after restart fails with this error a few times before successfully starting:
```
█▀▀ █▀█   █▀▀ █▀▀ ▄▀█ ▀█▀ █ █ █▀█ █▀▀   █▀▀ █   ▄▀█ █▀▀█▄█ █▄█   █▀  ██▄ █▀█  █  █▄█ █▀▄ ██▄   █▀  █▄▄ █▀█ █▄█     █▀█ █▀▀ █   ▄▀█ █▄█   █▀█ █▀█ █▀█ ▀▄▀ █▄█     █▀▄ ██▄ █▄▄ █▀█  █    █▀▀ █▀▄ █▄█ █ █  █
GO Feature Flag Relay Proxy
_____________________________________________
panic: impossible to retrieve the flags, please check your configuration: Get "https://api.github.com/repos/repo/config-file.yaml?ref=main": dial TCP <ip-address>:443: connect: connection refused
goroutine 1 [running]:
main.main()	
/home/runner/work/go-feature-flag/go-feature-flag/cmd/relayproxy/main.go:85 +0xc95
```
maybe this can help

**Comment by lorelei-rupp-imprivata** [comment]
Yeah its hard to know if this issue is the cause of a rate limit, GIThub sends back headers I think that say you are being ratel imited, not sure if we can get that information logged

**Comment by lorelei-rupp-imprivata** [comment]
In one of our environments, this pod has restarted 606 times! 

feature-flag-relay-proxy-5d5c4c5cb6-25qd2                         2/2     Running                      606 (14d ago)   16d

**Comment by thomaspoignant** [comment]
You are right @lorelei-rupp-imprivata GitHub is exposing some headers that give information about the rate limiting.

![Screenshot 2024-05-24 at 16 40 07](https://github.com/thomaspoignant/go-feature-flag/assets/17908063/f33f6728-7ee4-4e0a-9023-f74d33cef10f)

I am particularly interested in the headers
- `X-Ratelimit-Reset` that gives the time at which the current rate limit window resets in UTC epoch **seconds.** and
- `X-RateLimit-Remaining`: The number of requests remaining in the current rate limit window.

Because we can stop trying any call until `X-Ratelimit-Reset` if `X-RateLimit-Remaining`.
I will create an issue for that.


One more piece of information that can be interesting for you about the crashes. 
You can avoid them by setting `startWithRetrieverError: true` in your configuration file for the relay-proxy. 
With this property, the relay-proxy will not crash when starting if he is not able to read the flags, so the default value will be used when trying to evaluate the flag.

**Comment by Volodymyr-Maiboroda-Imprivata** [comment]
> You are right @lorelei-rupp-imprivata GitHub is exposing some headers that give information about the rate limiting.
> 
> ![Screenshot 2024-05-24 at 16 40 07](https://private-user-images.githubusercontent.com/17908063/333637026-f33f6728-7ee4-4e0a-9023-f74d33cef10f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjM4MzYsIm5iZiI6MTcxNjU2MzUzNiwicGF0aCI6Ii8xNzkwODA2My8zMzM2MzcwMjYtZjMzZjY3MjgtN2VlNC00ZTBhLTkwMjMtZjc0ZDMzY2VmMTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE1MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYTVlOWJlOTNjZmM4YTEzNGQxZDMyY2E4YjdkNzg1MGRlYTUxMTRkMDk2OGIyODRiYTIzM2QzMTAyNDMzZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ETOWW7iD5e11JttKuVU95h94rfAbJ_8WsWancvKVgs0)
> 
> I am particularly interested in the headers
> 
> * `X-Ratelimit-Reset` that gives the time at which the current rate limit window resets in UTC epoch **seconds.** and
> * `X-RateLimit-Remaining`: The number of requests remaining in the current rate limit window.
> 
> Because we can stop trying any call until `X-Ratelimit-Reset` if `X-RateLimit-Remaining`. I will create an issue for that.
> 
> One more piece of information that can be interesting for you about the crashes. You can avoid them by setting `startWithRetrieverError: true` in your configuration file for the relay-proxy. With this property, the relay-proxy will not crash when starting if he is not able to read the flags, so the default value will be used when trying to evaluate the flag.

I saw `startWithRetrieverError: true` in the configuration, but it will be harder to identify the issue with the GitHub retriever and feature flags won't work correctly. So, it doesn't help in our use case.

**Comment by Volodymyr-Maiboroda-Imprivata** [comment]
@thomaspoignant I added
```
    DEBUG:
      value: 'true
```
which should provide more information on failure (as I read in the documentation), but as you can see from my example, it doesn't provide anything specific. I wonder, if response headers can be added to logs when debug is enabled?

**Comment by thomaspoignant** [comment]
I understand.
My recommendation for the short term is to try to use a GitHub App Token in the retriever _(this should normally work)_ to have a higher rate limit.

In the meantime, if you want to work on dealing with the rate limiter there is this issue open #1916.

I have also opened an issue to add the headers in the error message #1917.

**Comment by thomaspoignant** [comment]
I have opened a PR for the logs #1919 if you want to review it.
