### ISSUE TITLE
(change) Change cache in openfeature java provider 

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1985]
### Motivation

As mentioned by @liran2000 in this PR comment https://github.com/open-feature/java-sdk-contrib/pull/821#discussion_r1636452408 the cache system used in the java provider is from `guava` and they discouraged using it and recommend using [`caffeine`](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/cache/package-summary.html) instead.

Since it is a breaking change we didn't want to introduce it to the provider.

When going for version `1.0.0` of the provider we should consider changing the cache mechanism in favour of `caffeine`.

### Requirements

We should refactor the provider to use [`caffeine`](https://github.com/ben-manes/caffeine) instead of the `guava` cache.

To do so we will have to introduce a breaking change in the `GoFeatureFlagProviderOptions` file, to change the type of the `cacheBuilder` option.

When doing that we should ensure a proper documentation on how to migrate from `guava` to `caffeine`.

**Comment by matheusverissimo** [comment]
Hey @thomaspoignant, can I get assigned to this issue? I'm currently working on it and I think I can submit a PR adressing this change in a day or two.

**Comment by thomaspoignant** [comment]
Sure, I'll affect it to you.

**Comment by matheusverissimo** [comment]
Do you have any suggetion on where to document the breaking change of `CacheBuilder` to `Caffeine` on `GoFeatureFlagProviderOptions`?

There is no other change like that already documented and the README file doesn't seems the right place to me.

**Comment by matheusverissimo** [comment]
### Quick update

As I was testing the change, I've came across a test failure on `should_resolve_from_cache_max_size` in `GoFeatureFlagProviderTest`.

The last assertion was failing, as the value received from the call to retrieve the boolean also came from the cache, as did the string just before. Debugging the code, I understood that this is a race condition, since placing a Thread sleep right before the assertion makes the test pass successfully. 

```java
Thread.sleep(1000L);
got = client.getBooleanDetails("bool_targeting_match", false, this.evaluationContext);
assertEquals(want, got);
``` 

Unlike Guava, Caffeine does not guarantee that the cache size never exceeds the specified limit at any time due to important differences in the eviction algorithm compared to Guava. 

Because of this, I believe it makes sense to remove the last assertion from this test case, if you allow me.

More about these differences can be found here:
[Caffeine Wiki - Guava](https://github.com/ben-manes/caffeine/wiki/Guava)
[Ben Menes Comment on Caffeine cache temporarily exceeding maximum size](https://github.com/ben-manes/caffeine/issues/420#issuecomment-630377203)

**Comment by matheusverissimo** [comment]
@thomaspoignant

**Comment by thomaspoignant** [comment]
@matheusverissimo sorry for some reason I missed your comments before today 😔

Let me try to answer your questions.

> Do you have any suggetion on where to document the breaking change of CacheBuilder to Caffeine on GoFeatureFlagProviderOptions?
>
>There is no other change like that already documented and the README file doesn't seems the right place to me.

First of all when you open the PR in the contrib repo be sure to prefix your PR title with `feat!:`, the `!` will tell `release-please` the library in charge of releasing that this is a breaking change and it will bump correctly the version number.

Beside that, I think we can add a `# Breaking Changes` section in the `README` to notify that it happened.
And I think we should also add the same section in the website (in this [file](https://github.com/thomaspoignant/go-feature-flag/blob/main/website/docs/openfeature_sdk/server_providers/openfeature_java.mdx)).

> Because of this, I believe it makes sense to remove the last assertion from this test case, if you allow me.

If Caffeine is not evicting cache entry the same way it makes sense to me to remove the last assertion.
Just be sure to add a comment in the PR to explain why we are removing if someone is checking why.
