### ISSUE TITLE
(question) Getting a Type MiSMATCH Error

### ISSUE THREAD

**Issue by h-abinaya28** [thomaspoignant/go-feature-flag#2453]
### Your question

Hi, 

I am following the example given in the retriever_configmap/ 
and When I try to print the 

`user1 := ffcontext.NewEvaluationContextBuilder("").AddCustom("tenant", tenantid).Build()`

```
allflags := fclient.AllFlagsState(user1)
	logger().Infof("HA: allflags: %+v", allflags.GetFlags())
```

My CM looks like this:
`apiVersion: v1
data:
  ff.yaml: |
    feature:
      variations:
        default_var: false
        false_var: false
        true_var: true
      targeting:
        - query: tenant eq "ecsdcdwcfkrsfa"
          percentage:
            false_var: 0
            true_var: 100
      defaultRule:
        variation: default_var
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-03T20:03:03Z"
  name: goff
  namespace: sdeyagond
  resourceVersion: "567712280"
  uid: 58fa02f9-4c50-436b-bb9b-da4bed60e8b3`

I get this: 

`{"level":"info","ts":"2024-10-03T21:06:27.641Z","caller":"sample/sample_ad.go:85","msg":"HA: allflags: map[feature:{Value:<nil> Timestamp:1727989587 VariationType:SdkDefault TrackEvents:true Failed:true ErrorCode:TYPE_MISMATCH ErrorDetails: Reason:ERROR Metadata:map[]}]"}
`
Anyone has pointers on what must be wrong in here?

**Comment by thomaspoignant** [comment]
Hello @h-abinaya28 thanks for raising this issue.
I have looked at your problem and the issue is that you are sending an empty `targetingKey` when creating your evaluation context.

This is not supported by GO Feature Flag, you are always needed to set a non-empty key.

That being said the error your receive is not correct and it should be a bit more explicit.
The reason you have a `TYPE_MISMATCH` is because of this check
https://github.com/thomaspoignant/go-feature-flag/blob/b5144e33b95888835509a100620eb99383fef286/internal/flagstate/flag_state.go#L41

In case of error, the value is nil and does not match any of the condition of the case, so we return a wrong error here.

I'll keep this issue open to be sure that we return an explicit error in your case.
BUT you just have to set a `targetingKey` and you should not have any problem.

```go
user1 := ffcontext.NewEvaluationContextBuilder("my-key").AddCustom("tenant", tenantid).Build()
```

**Comment by thomaspoignant** [comment]
I have opened a PR #2455 about this to return a correct error.

**Comment by h-abinaya28** [comment]
Thank you for the clarification @thomaspoignant . However, I did try the example version from the retriever_configmap/ where one of the user has an empty targeting key and it works fine in minikube. Shouldn't it be throwing an error too?

**Comment by h-abinaya28** [comment]
Oh, my bad, I mistakenly removed the target key. However, when I built the code and ran it, it ran without complains.. Anyway, I will verify this behaviour again and raise a question, if it still is the case. 

Thank you for the response!
