### ISSUE TITLE
(bug) <Fetching json flags as a yaml>

### ISSUE THREAD

**Issue by OnigiriJack** [thomaspoignant/go-feature-flag#394]
### Observed behavior

I am trying to fetch a json flag, but the retriever is fetching the flag as a yaml and not a json.

error:

```
2022/11/01 20:50:40 error: impossible to update the cache of the flags: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `` into float64`
```
Flag setup: 

```go
	err = ffclient.Init(ffclient.Config{
		PollingInterval: 3 * time.Second,
		Retriever: &httpretriever.Retriever{
			URL: "http://localhost:4100/feature_flags.json",
		},
	})
```

JSON at endpoint:
```json
{
  "organizationSettings": {
    "default": "",
    "disable": false,
    "false": "",
    "percentage": 100,
    "rule": "",
    "trackEvents": false,
    "true": "",
    "version": ""
  },
  "publishCompanyUpserts": {
    "default": "",
    "disable": false,
    "false": "",
    "percentage": 100,
    "rule": "",
    "trackEvents": false,
    "true": "",
    "version": ""
  }
}
```

### Expected Behavior

I expect the flag to be retrieved from the endpoint without an error.

**Comment by thomaspoignant** [comment]
Hello @OnigiriJack,

thanks for raising this issue, this is an expected behavior, if you don't specify the `fileFormat` in your `Init` it will use `YAML` as default.

You can check the field `FileFormat` in this doc: https://docs.gofeatureflag.org/docs/configuration#configuration-fields

>  Format of your configuration file. Available formats are yaml, toml and json, if you omit the field it will try to unmarshal the file as a yaml file.

In your case to make it work you should do it this way.
```go
        err = ffclient.Init(ffclient.Config{
		PollingInterval: 3 * time.Second,
		Retriever: &httpretriever.Retriever{
			URL: "http://localhost:4100/feature_flags.json",
		},
		FileFormat: "json",
	})
```

I think we can do better than that in the future by detecting the extension, but this is not a behavior we support now.
